title: Chaos RAG
description: A RAG application that allows you to interact with a knowledge base based on Edward Lorenz's book

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

readme_index:
  enabled: true
  remove_originals: false

color_scheme: dark

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

include:
  - README.md

exclude:
  - .git
  - .gitignore
  - .devcontainer
  - src/